// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJS863FxrHHLQZlomMiVb_UqzNlthTuY4',
    appId: '1:779737086240:web:62d47345c6f96d031bbf45',
    messagingSenderId: '779737086240',
    projectId: 'sandbox-cafeteria-bianchys',
    authDomain: 'sandbox-cafeteria-bianchys.firebaseapp.com',
    storageBucket: 'sandbox-cafeteria-bianchys.appspot.com',
    measurementId: 'G-9C14BF7SBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hTPbjaKqUtRes8fDH-eB_M8midc7O9M',
    appId: '1:779737086240:android:363d8495d49a75021bbf45',
    messagingSenderId: '779737086240',
    projectId: 'sandbox-cafeteria-bianchys',
    storageBucket: 'sandbox-cafeteria-bianchys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaRlF6bO2tJFEewNOJwE0ji9Cc6DU0qMI',
    appId: '1:779737086240:ios:f3c1dd2505f7028c1bbf45',
    messagingSenderId: '779737086240',
    projectId: 'sandbox-cafeteria-bianchys',
    storageBucket: 'sandbox-cafeteria-bianchys.appspot.com',
    iosBundleId: 'com.example.cafeteriaApp',
  );
}
